apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{cnvrg_router.svc_name}}"
  namespace: "{{ansible_operator_meta.namespace}}"
spec:
  hosts:
  - "{{(cnvrg_router.svc_name + '.' + cluster_domain).split(':')[0] }}"
  gateways:
  - "{{istio.gw_name}}"
  http:
  - retries
      attempts: {{ istio.retries_attempts | default ('5') }}
      perTryTimeout: {{ istio.per_try_timeout | default ('1s') }}
    route:
    - destination:
        port:
          number: {{cnvrg_router.port}}
        host: "{{cnvrg_router.svc_name +'.' + ansible_operator_meta.namespace + ".svc.cluster.local" }}"