---
kibana:
  enabled: "true"
  svc_name: kibana
  port: 5601
  image: "docker.elastic.co/kibana/kibana-oss:6.2.4"
  node_port: 30601
  cpu_request: 500m
  memory_request: 500Mi
  cpu_limit: 1
  memory_limit: 2000Mi